### ISSUE TITLE
Usage with laravel-adjacency-list?

### ISSUE THREAD

**Issue by jp2masa** [staudenmeir/eloquent-has-many-deep#149]
Is this library compatible with [laravel-adjacency-list](https://github.com/staudenmeir/laravel-adjacency-list)?

I'm trying the following code but the relationship returns an empty array:

```php
class Category extends Model
{
    use HasFactory;
    use HasRecursiveRelationships;
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    ...

    public function directSpecifications()
    {
        return $this->belongsToMany(
            Specification::class,
            CategorySpecification::class
        );
    }

    public function specifications()
    {
        return $this->hasManyDeepFromRelations(
            $this->newRelatedInstance(Category::class)->ancestorsAndSelf(),
            $this->newRelatedInstance(Category::class)->directSpecifications()
        );
    }
}
```

**Comment by staudenmeir** [comment]
Unfortunately, this kind of combination is not possible because recursive relationships can't be concatenated like "normal" relationships.

What you need instead is a `BelongsToManyOfAncestors` relationship (equivalent to [`BelongsToManyOfDescendants`](https://github.com/staudenmeir/laravel-adjacency-list#belongstomanyofdescendants)) and I'm working on that. I'll give you an update when the relationship is ready.

**Comment by jp2masa** [comment]
OK, thanks!

**Comment by staudenmeir** [comment]
I just released new versions for both packages that add support for relationships like yours.

You only need to remove the first `->newRelatedInstance(Category::class)`:

```php
class Category extends Model
{
    public function specifications()
    {
        return $this->hasManyDeepFromRelations(
            $this->ancestorsAndSelf(),
            $this->newRelatedInstance(Category::class)->directSpecifications()
        );
    }
}
```
