### ISSUE TITLE
Save model on HasOneDeep

### ISSUE THREAD

**Issue by machacekmartin** [staudenmeir/eloquent-has-many-deep#248]
Hi! 
Similiar to how `HasOne` allows for `->save($model)` assignment, I would expect to have the same capability on `HasOneDeep` relations. Am I missing something or is it impossible to implement?

Example in `User` model
```php
public function company(): HasOneDeep
{
    return $this->hasOneDeep(Company::class, ['company_user']);
}
```

`company_user` being a n:m table of just `company_id` and `user_id` pairs.

I would expect to be able to use `$user->company()->save($company)`, but I haven't found any methods that would support this behavior.

_(fyi dont look at the real world usage of this example, its just for illustration)._

**Comment by staudenmeir** [comment]
Hi @machacekmartin,
It's not possible to implement such a method. Consider the example from the [README](https://github.com/staudenmeir/eloquent-has-many-deep?tab=readme-ov-file#hasonedeep):
`$country->latestComment()->save(new Comment(['text' => 'foo']))` wouldn't work because the method can't know to which post the comment belongs. It works for `HasOne` relationships because there aren't any intermediate tables.

It would be possible in your very specific example, but only because it's actually a `BelongsToMany` relationship (that provides methods like `attach()`).
